name: Codesign with Microsoft Trusted Signing
description: Sign Windows files with Microsoft Trusted Signing Service
runs:
  using: "composite"
  steps:
    - uses: azure/trusted-signing-action@1d365fec12862c4aa68fcac418143d73f0cea293 # v0
      with:
        azure-tenant-id: ${{ inputs.azure_tenant_id }}
        azure-client-id: ${{ inputs.azure_client_id }}
        azure-client-secret: ${{ inputs.azure_client_secret }}
        endpoint: https://eus.codesigning.azure.net/
        trusted-signing-account-name: tsa-tensorplay-apps
        certificate-profile-name: git-xet-windows
        files: ${{ inputs.file }}
        file-digest: SHA256
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256
        exclude-environment-credential: false
        exclude-workload-identity-credential: true
        exclude-managed-identity-credential: true
        exclude-shared-token-cache-credential: true
        exclude-visual-studio-credential: true
        exclude-visual-studio-code-credential: true
        exclude-azure-cli-credential: true
        exclude-azure-powershell-credential: true
        exclude-azure-developer-cli-credential: true
        exclude-interactive-browser-credential: true
inputs:
  file:
    required: true
    type: string
  azure_tenant_id:
    required: true
    type: string
  azure_client_id:
    required: true
    type: string
  azure_client_secret:
    required: true
    type: string
